apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-jenkins-pv
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: jenkins
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/data/jenkins"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists

